name: msnag2
channels:
  - saareliad  # should be explicitly set first, to gain priority over pytorch, however anaconda got channel priority problems (*)
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - se-msnag2  # cuda aware openmpi
  - magma-cuda102
  - numpy 
  - ninja 
  - pyyaml 
  - mkl 
  - mkl-include 
  - setuptools 
  - cmake 
  - cffi
  - jupyterlab
  - scikit-learn
  - ipython
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - sympy
  - pybind11  # For binding c++ code to python, may be used to increace performance.
  - graphviz  # For partitioning visualization
  - python-graphviz  # For partitioning visualization
  - networkx  # For partitioning
  - seaborn
  - pip:
    - git+https://github.com/networkx/networkx-metis.git  # For partitioning
    - matplotlib
    - nbmerge
    - pytest-xdist
    - flake8
    - autopep8
    - rope
    - click
    - transformers
    - ptvsd
